name: CI
      
# Controls when the action will run.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the output time
        run: echo '${{ secrets.SECRET_OWASP_DT_KEY }}'
