name: CI
      
# Controls when the action will run.
on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    env:
      MY_VARIABLE: ${{ env.LANG }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Repository Variable
        run: echo "My variable value is $MY_VARIABLE"
